---
title: "Result analysis"
output:
  html_document:
    df_print: paged
    toc_depth: '2'
  html_notebook: default
  pdf_document:
    highlight: zenburn
    keep_tex: yes
params:
  run_test: no
  use_kable: no
---

```{r setup, include=FALSE}

library(knitr)
library(ggsci)
library(tidyverse)
library(glue)
library(cowplot)
library(ggrepel)

source("functions_learning.R")
source("init.R")

knitr::opts_chunk$set(
  echo = FALSE, 
  message = FALSE, 
  warning = FALSE,
  fig.width=fig.width.baseline*output.size, 
  out.width=out.width.default)

theme_set(theme_bw(base_size = 9.5) + theme(legend.title=element_blank()))

```


We use this file to compare the final results from analysis_learningrates_corrections.

```{r load all results}

all_learnig_rates_results <- list()

for(currency in relevant_currencies){
  all_learnig_rates_results[[paste(currency,"real")]]  <- read_csv(paste0("output/results/learning_rate_results_",currency,"_real.csv"))
  all_learnig_rates_results[[paste(currency,"nominal")]]  <- read_csv(paste0("output/results/learning_rate_results_",currency,"_nominal.csv"))
}

all_results <- all_learnig_rates_results %>%   
  reduce(bind_rows) %>% 
  distinct() %>% 
  mutate(
    type = fct_relevel(type, "uncorrected_project_weighted", "uncorrected_markted_weighted", "corrected_markted_weighted"),
    type_label = type,
    type_label = fct_recode(type_label,
       "Uncorrected \n project-wt." = "uncorrected_project_weighted",
       "Uncorrected \n market share-wt." = "uncorrected_markted_weighted",
       "Fx-corrected \n market share-wt." = "corrected_markted_weighted"),
    interval = fct_relevel(interval, factor_order_intervals),
    interval = fct_recode(interval,!!!plot_stips_label)
    ) %>% 
  arrange(currency, interval)


```



```{r all_results_plot, fig.cap="Learning rates plot", fig.asp=0.4}


plot_labels = all_results %>% 
  expand(version, interval) %>% 
  add_column(label = letters[seq( from = 1, to = 6 )])
  
all_learnig_rates_results_plot = all_results %>% 
  ggplot(mapping = aes(x = type_label, y = estimate, fill = currency)) +
    geom_col(position = "dodge2") +
    geom_text(. %>% filter(type_label == type_label), mapping = aes(y = estimate/2, label = round(estimate)), 
              position = position_dodge(0.9), col = "white", size = 2.8, angle = 90) +
    geom_text(data = plot_labels, mapping = aes(x = 0.6, y = 43, label = label), fontface = "bold") +
    scale_y_continuous(limits = c(0,44), expand = expand_scale(mult = c(0, 0.1))) +
    labs(
      y = paste0("Learning rate in %")) +
    theme(
      axis.title.x = element_blank(),
      panel.grid.major = element_blank(),
      legend.position="bottom",
      legend.spacing.x = unit(0.1, 'cm')) +
    guides(
      fill = guide_legend(nrow = 1)) +
    facet_grid(version ~ interval, switch = "y") +
    scale_fill_manual(values = plot_colours_currencies)

all_learnig_rates_results_plot


```


```{r summary table}

all_types <- all_results$type %>% levels()
all_intervals <- all_results$interval %>% levels()

library(kableExtra)

tables <- list()

# Subtitle per step 1,2,3
for(type in all_types){
  
  tables[[type]] <- bind_cols(
     filter(all_results, type == !!type, interval == all_intervals[1]),
     filter(all_results, type == !!type, interval == all_intervals[2]),
     filter(all_results, type == !!type, interval == all_intervals[3])
  ) %>% 
    arrange(version, currency) %>% 
    select(currency, estimate, CI, R2, estimate1, CI1, R21,estimate2, CI2, R22)
    
  kable_table <- tables[[type]] %>% 
    kable(caption = glue("Results for {type}.")) %>%
    kable_styling() %>% 
    add_header_above(c(" " =1, 
                       "Full 10-year interval (2006-2016)" = 3, 
                       "First 5-year interval (2006-2011)" = 3, 
                       "Second 5-year interval (2011-2016)" = 3)) %>% 
    kableExtra::group_rows("nominal", 1, 6) %>%
    kableExtra::group_rows("real", 7, 12)
  
  print(kable_table)
  
  write_excel_csv(
    tables[[type]],
    glue("output/reports_tables/results_table_{type}.csv"))
  
}


```

